language: c++
sudo: false
dist: trusty
branches:
  only:
  - master
  - "/^[0-9].*$/"
addons:
  apt:
    packages:
    - libc-ares-dev
    - libcurl4-openssl-dev
    - libev-dev
    - curl
    - gettext
    - jq
    - git
script:
- "./build"
deploy:
  provider: releases
  file_glob: true
  file: https-dns-proxy_*_amd64.deb
  skip_cleanup: true
  api_key: "$GITHUB_TOKEN"
  verbose: true
  on:
    tags: true
env:
  secure: bb8emCTaq6yCwJMLx5EisSR0G+mzCMdAKmvx0zrNB3wVLwalidmFFa0fpGUh0SPWQIE/ODoDT8lcrvNUXNgjbc90TyP8RTm2gXyAnN2s6k+3a5yqQ9XH11PqXQBA5rWkyoHBKpmysrhaGhiV2n6Dio6p/cZIlmVY1Clezx6e8y3GYHgKcqwvdHsrGAbcVRjWek+EWbDCGaOk/laYGrM5p4Bi0k72RKQV5QTlF7DAnFIP9IXPIVR5nQa029ss9oiSZuGKxI336bbcRZN9XwlOYCVUx0UQCocVoo0R5kESlni+bZz3XOtOCOdFKtdCo3QxxEz6BvIK2iJJfBbVXeKHVLTUCIyh+W7nlTC016M9tfRJZUm1Jg/bhrf82P/3+ibN3BKuHE7Cvkm8EPHH8DOp6gHGJ2so9LT1O77KuG05pGj048oFe2CBnPW5HyioKMGGt2tJ1574/Lm7PcwoV0WklA6s5AdqzdyA5LZkY5u9YPW9BqkFZKD6wIKGnwPD0z5V76XaUArVMz5vjrTcPgh++p/uAmYzjHRKMEZtvBChQFqSDhh+g3ED2S1ify1y86rhDzzc66k1ILgTgP/SWgT/XSavqYndNw40xl6KAyE9JlV+ZaVvtUn11xgIXSnfI9vqZMqz1WeGd8qvQUhitWb77A7lLptld0t2xY0OJoC6OQM=
